
--CONFIGURACIÓN DE PARÁMETRO PARA PODER CREAR ROLES CON LOS NOMBRES PERSONALIZADOS
alter session set "_ORACLE_SCRIPT"=true;


/************************************************************************/

-------------------- CREACIÓN DE ROL ADMINISTRADOR ----------------------------

/************************************************************************/

CREATE ROLE administrador;

GRANT ALL PRIVILEGES TO administrador;

GRANT INSERT ON C##TIENDA.TBL_USUARIO TO ADMINISTRADOR;
GRANT UPDATE ON C##TIENDA.TBL_USUARIO TO ADMINISTRADOR;
GRANT DELETE ON C##TIENDA.TBL_USUARIO TO ADMINISTRADOR;

GRANT SELECT
     ,INSERT,UPDATE,DELETE ON C##TIENDA.TBL_CATEGORIA TO ADMINISTRADOR; 
     
     GRANT SELECT
     ,INSERT,UPDATE,DELETE ON C##TIENDA.TBL_SUBCATEGORIA TO ADMINISTRADOR; 
      GRANT SELECT ON C##TIENDA.TBL_SUBCATEGORIA TO ADMINISTRADOR; 


commit;
select * from all_users;

/************************************************************************/

-------------------- CREACIÓN DE ROL VENDEDOR ----------------------------

/************************************************************************/

CREATE ROLE vendedor;

-- ASIGNANDO LOS PERMISOS NECESARIOS A LAS TABLAS QUE EL ROL VENDEDOR
-- TENDRÁ ACCESO

GRANT SELECT ON C##TIENDA.TBL_USUARIO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_ROL TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_CLIENTE TO vendedor; 


GRANT INSERT ON C##TIENDA.TBL_BITACORA TO vendedor; 

GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_KARDEX TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_PEDIDO TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_VENTA TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_VENTA_DETALLE TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_SERIE TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIENDA_PRODUCTO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_MOVIMIENTO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_PAGO TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_UBICACION TO vendedor; 

/*PERMISOS QUE EL ROL VENDEDOR TENDRÁ EN LA TABLAS 
USUARIO 
PERSONA
EMPLEADO 
TURNO_TIENDA_EMPLEADO
TURNO_TIENDA
TURNO
ROL
TIPO_DOCUMENTO

*/

GRANT SELECT ON C##TIENDA.TBL_USUARIO TO vendedor; 
GRANT SELECT,INSERT,UPDATE ON C##TIENDA.TBL_PERSONA TO vendedor;
GRANT SELECT ON C##TIENDA.TBL_EMPLEADO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TURNO_TIENDA_EMPLEADO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_DOCUMENTO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_STATUS TO vendedor; 
/************************************************************************/
commit;
-------------------- CREACIÓN DE ROL ENCARGADO ----------------------------

/************************************************************************/

CREATE ROLE encargado;

-- ASIGNANDO LOS PERMISOS NECESARIOS A LAS TABLAS QUE EL ROL ENCARGADO
-- TENDRÁ ACCESO

GRANT SELECT ON C##TIENDA.TBL_USUARIO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_ROL TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_CLIENTE TO vendedor; 
GRANT INSERT ON C##TIENDA.TBL_BITACORA TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_KARDEX TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_PEDIDO TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_VENTA TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_VENTA_DETALLE TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_SERIE TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIENDA_PRODUCTO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_MOVIMIENTO TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_PAGO TO vendedor; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_UBICACION TO vendedor; 
GRANT SELECT ON C##TIENDA.TBL_USUARIO TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_ROL TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_CLIENTE TO cliente; 
GRANT INSERT ON C##TIENDA.TBL_BITACORA TO cliente; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_PEDIDO TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_TIENDA_PRODUCTO TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_PAGO TO cliente; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_UBICACION TO cliente;      
/************************************************************************/

/*PERMISOS QUE EL ROL ENCARGADO TENDRÁ EN LA TABLAS 
USUARIO 
PERSONA
EMPLEADO 
TURNO_TIENDA_EMPLEADO
TURNO_TIENDA
TURNO
ROL
TIPO_DOCUMENTO

*/
select role from dba_roles;

GRANT SELECT ON C##TIENDA.TBL_USUARIO TO ENCARGADO; 
GRANT SELECT,INSERT,UPDATE ON C##TIENDA.TBL_PERSONA TO ENCARGADO; 
GRANT SELECT,UPDATE ON C##TIENDA.TBL_EMPLEADO TO ENCARGADO; 
GRANT SELECT,UPDATE ON C##TIENDA.TBL_TURNO_TIENDA_EMPLEADO TO ENCARGADO; 
GRANT SELECT,UPDATE ON C##TIENDA.TBL_TURNO_TIENDA TO ENCARGADO; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_DOCUMENTO TO ENCARGADO; 
GRANT SELECT ON C##TIENDA.TBL_STATUS TO ENCARGADO; 
GRANT SELECT ON C##TIENDA.TBL_ROL TO ENCARGADO; 
GRANT SELECT ON C##TIENDA.TBL_TURNO TO ENCARGADO; 


commit;

/************************************************************************/

-------------------- CREACIÓN DE ROL CLIENTE ----------------------------

/************************************************************************/

CREATE ROLE cliente;

-- ASIGNANDO LOS PERMISOS NECESARIOS A LAS TABLAS QUE EL ROL CLIENTE
-- TENDRÁ ACCESO

GRANT SELECT ON C##TIENDA.TBL_USUARIO TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_ROL TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_CLIENTE TO cliente; 
GRANT INSERT ON C##TIENDA.TBL_BITACORA TO cliente; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_PEDIDO TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_TIENDA_PRODUCTO TO cliente; 
GRANT SELECT ON C##TIENDA.TBL_TIPO_PAGO TO cliente; 
GRANT SELECT
     ,INSERT ON C##TIENDA.TBL_UBICACION TO cliente; 

-- CREACIÓN DE USUARIO CLIENTE GENÉRICO PARA LA CREACIÓN DEL PEDIDO
-- EL ALTA DEL CLIENTE QUE HACE LA COMPRA SERÁ A NIVEL DE APLICACIÓN
-- ES DECIR QUE TODOS LOS CLIENTES QUE PIDAN WEB ESTARÁN UTILIZANDO ESTE ROL Y 
-- USUARIO

commit;
