COMMIT;

-------------SECUENCIAS---------------
---persona, EMPIEZA CON 1153, YA QUE SE HABÍAN INSERTADO DATOS ANTES 
CREATE SEQUENCE SEC_TBL_PERSONA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 1153
INCREMENT BY 1
CACHE 20;

--TIPO_DOCUMENTO

CREATE SEQUENCE SEC_TBL_TIPO_DOCUMENTO
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 4
INCREMENT BY 1
CACHE 20;

--ROL

CREATE SEQUENCE SEC_TBL_ROL
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 5
INCREMENT BY 1
CACHE 20;

--TURNO

CREATE SEQUENCE SEC_TBL_TURNO
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 4
INCREMENT BY 1
CACHE 20;

--EMPLEADO

CREATE SEQUENCE SEC_TBL_EMPLEADO
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

--USUARIO

CREATE SEQUENCE SEC_TBL_USUARIO
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 4
INCREMENT BY 1
CACHE 20;

--BITACORA

CREATE SEQUENCE SEC_TBL_BITACORA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;


----------------TRIGGERS---------------------




--T_TIPO_DOCUMENTO

create or replace  TRIGGER TGR_TIPO_DOCUMENTO
BEFORE INSERT ON TBL_TIPO_DOCUMENTO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
SELECT SEC_TBL_TIPO_DOCUMENTO.NEXTVAL INTO :New.ID_TIPO_DOCUMENTO  FROM DUAL;

END;
/


--T_TURNO

create or replace  TRIGGER TGR_TURNO
BEFORE INSERT ON TBL_TURNO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
SELECT SEC_TBL_TURNO.NEXTVAL INTO :New.ID_TURNO  FROM DUAL;

END;
/

--T_ROL

create or replace  TRIGGER TGR_ROL
BEFORE INSERT ON TBL_ROL REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
SELECT SEC_TBL_ROL.NEXTVAL INTO :New.ID_ROL  FROM DUAL;

END;
/

--T_PERSONA

create or replace  TRIGGER TGR_PERSONA
BEFORE INSERT ON TBL_PERSONA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
SELECT SEC_TBL_PERSONA.NEXTVAL INTO :New.ID_PERSONA  FROM DUAL;

END;
/

----T_EMPLEADO
create or replace  TRIGGER TGR_EMPLEADO
BEFORE INSERT ON TBL_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
SELECT SEC_TBL_EMPLEADO.NEXTVAL INTO :New.ID_EMPLEADO  FROM DUAL;

END;
/


----T_USUARIO
create or replace  TRIGGER TGR_USUARIO
BEFORE INSERT ON TBL_USUARIO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
SELECT SEC_TBL_USUARIO.NEXTVAL INTO :New.ID_USUARIO  FROM DUAL;

END;

/



















----T_PERSONA_BITACORA
--- insert
    create or replace  TRIGGER 
    TGR_BITACORA_AFTER_INSERT_PERSONA AFTER 
    INSERT ON TBL_PERSONA REFERENCING NEW AS NEW 
    OLD AS OLD FOR EACH ROW
    BEGIN  
        INSERT INTO TBL_BITACORA (ID_TRANSACCION,
        BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
        VALUES(
        SEC_TBL_BITACORA.NEXTVAL,
        'TBL_PERSONA',
        SYS_CONTEXT ('USERENV', 'OS_USER'),
        SYSDATE,
        'SE HA INGRESADO UN NUEVO REGISTRO CON LOS SIGUIENTES VALORES:'||
        ' ID_TIPO_DOCUMENTO= '||TO_CHAR (:NEW.id_tipo_documento)||
        ', PRIMER_NOMBRE= '|| TO_CHAR (:NEW.primer_nombre)||' , SEGUNDO_NOMBRE= '||
        TO_CHAR (:NEW.segundo_nombre)||', TERCER_NOMBRE= '||
        TO_CHAR (:NEW.tercer_nombre)||', PRIMERO_APELLIDO= '||
        TO_CHAR (:NEW.primero_apellido)||', SEGUNDO_APELLIDO= '||
        TO_CHAR (:NEW.segundo_apellido)||', DOCUMENTO= '||TO_CHAR (:NEW.documento)||
        ', NIT= '||TO_CHAR (:NEW.nit)||', FECHA_NACIMIENTO= '||
        TO_CHAR (:NEW.fecha_nacimiento)||', SEXO= '||TO_CHAR (:NEW.sexo)||
        ', TELEFONO= '||TO_CHAR (:NEW.telefono)||', EMAIL= '||TO_CHAR (:NEW.email)||
        ', RAZON_SOCIAL= '||TO_CHAR (:NEW.razon_social)||', DIRECCION= '||TO_CHAR (:NEW.direccion)||'.'
       );
    END;
    /
    
    ---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_PERSONA
AFTER DELETE ON TBL_PERSONA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_PERSONA',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
     'SE BORRARON LOS DATOS DEL REGISTRO CON ID = '|| TO_CHAR (:OLD.ID_PERSONA)||' 
    VALORES ATERIORES= '||'ID_TIPO_DOCUMENTO ='''|| TO_CHAR (:OLD.id_tipo_documento)||''', PRIMER_NOMBRE= '''||TO_CHAR (:OLD.primer_nombre)||''', SEGUNDO_NOMBRE= '''||
     TO_CHAR (:OLD.segundo_nombre)||''', TERCER_NOMBRE= '''||TO_CHAR (:OLD.tercer_nombre)||''', PRIMERO_APELLIDO= '''|| TO_CHAR (:OLD.primero_apellido)||''', SEGUNDO_APELLIDO= '''||
     TO_CHAR (:OLD.segundo_apellido)||''', DOCUMENTO= '''||TO_CHAR (:OLD.documento)||''', NIT= '''||TO_CHAR (:OLD.nit)||''', FECHA_NACIMIENTO= '''|| TO_CHAR (:OLD.fecha_nacimiento)||
     ''', SEXO= '''|| TO_CHAR (:OLD.sexo)||''', TELEFONO= '''|| TO_CHAR (:OLD.telefono)||''', EMAIL= '''||TO_CHAR (:OLD.email)||''', RAZON_SOCIAL= '''|| TO_CHAR (:OLD.razon_social)||
     ''', DIRECCION= '''|| TO_CHAR (:OLD.direccion)
   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_PERSONA
AFTER UPDATE ON TBL_PERSONA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_PERSONA',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
   SYSDATE,
    'SE ACTUALIZARON LOS DATOS DEL REGISTRO CON ID = '|| TO_CHAR (:OLD.ID_PERSONA)||' 
    VALORES ATERIORES= '||'ID_TIPO_DOCUMENTO ='''|| TO_CHAR (:OLD.id_tipo_documento)||''', PRIMER_NOMBRE= '''||TO_CHAR (:OLD.primer_nombre)||''', SEGUNDO_NOMBRE= '''||
     TO_CHAR (:OLD.segundo_nombre)||''', TERCER_NOMBRE= '''||TO_CHAR (:OLD.tercer_nombre)||''', PRIMERO_APELLIDO= '''|| TO_CHAR (:OLD.primero_apellido)||''', SEGUNDO_APELLIDO= '''||
     TO_CHAR (:OLD.segundo_apellido)||''', DOCUMENTO= '''||TO_CHAR (:OLD.documento)||''', NIT= '''||TO_CHAR (:OLD.nit)||''', FECHA_NACIMIENTO= '''|| TO_CHAR (:OLD.fecha_nacimiento)||
     ''', SEXO= '''|| TO_CHAR (:OLD.sexo)||''', TELEFONO= '''|| TO_CHAR (:OLD.telefono)||''', EMAIL= '''||TO_CHAR (:OLD.email)||''', RAZON_SOCIAL= '''|| TO_CHAR (:OLD.razon_social)||
     ''', DIRECCION= '''|| TO_CHAR (:OLD.direccion)||
     
     
     'A VALORES NUEVOS= ID_TIPO_DOCUMENTO ='''|| TO_CHAR (:NEW.id_tipo_documento)||''', PRIMER_NOMBRE='''||TO_CHAR (:NEW.primer_nombre)||''', SEGUNDO_NOMBRE'''||
     TO_CHAR (:NEW.segundo_nombre)||''', TERCER_NOMBRE='''||TO_CHAR (:NEW.tercer_nombre)||''', PRIMERO_APELLIDO'''|| TO_CHAR (:NEW.primero_apellido)||''', SEGUNDO_APELLIDO'''|| TO_CHAR (:NEW.segundo_apellido)||
     ''', DOCUMENTO='''||TO_CHAR (:NEW.documento)||''', NIT='''||TO_CHAR (:NEW.nit)||''', FECHA_NACIMIENTO='''|| 'TO_DATE('||TO_CHAR (:NEW.fecha_nacimiento)||''',YYYY-MM-DD HH24:MI:SS'')'||
     ''', SEXO='''|| TO_CHAR (:NEW.sexo)||''', TELEFONO='''|| TO_CHAR (:NEW.telefono)||''', EMAIL='''||TO_CHAR (:NEW.email)||''', RAZON_SOCIAL='''|| TO_CHAR (:NEW.razon_social)||
     ''', DIRECCION='''|| TO_CHAR (:NEW.direccion)
     );
END;
/


----COMPILADO 



----T_EMPLEADO_BITACORA
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_EMPLEADO
AFTER INSERT ON TBL_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_EMPLEADO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    
      'SE IGRESÓ UN NUEVO REGISTRO CON LOS VALORES= '||' ID_PERSONA ='''|| TO_CHAR (:NEW.ID_PERSONA)||''', ID_STATUS='''||TO_CHAR (:NEW.ID_STATUS)||
     ''', FECHA_INGRESO='''||TO_CHAR (:NEW.fecha_ingreso)
  
   );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_EMPLEADO
AFTER DELETE ON TBL_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_EMPEADO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    'SE ELIMINÓ UN REGISTRO CON ID= '|| TO_CHAR (:OLD.ID_EMPLEADO)||'LOS VALORES= ID_PERSONA ='''|| TO_CHAR (:OLD.ID_PERSONA)||''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||
     ''', FECHA_INGRESO='''||TO_CHAR (:OLD.fecha_ingreso)||'.'
   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_EMPLEADO
AFTER UPDATE ON TBL_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_EMPLEADO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    
     'SE ACTUALIZARON LOS DATOS DEL REGISTRO CON ID= '||TO_CHAR (:OLD.ID_EMPLEADO)||' VALORES ANTERIORES= ID_PERSONA ='''|| TO_CHAR (:OLD.ID_PERSONA)||''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||
     ''', FECHA_INGRESO='''||TO_CHAR (:OLD.fecha_ingreso)||
     'A VALORES NUEVOS= ID_PERSONA ='''|| TO_CHAR (:NEW.ID_PERSONA)||''', ID_STATUS='''||TO_CHAR (:NEW.ID_STATUS)||
     ''', FECHA_INGRESO='''|| 'TO_DATE('||TO_CHAR (:NEW.fecha_ingreso)||'.'
     );
END;
/




----T_TIPO_DOCUMENTO
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_TIPO_DOCUMENTO
AFTER INSERT ON TBL_TIPO_DOCUMENTO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TIPO_DOCUMENTO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
      'SE IGRESÓ UN NUEVO REGISTRO CON LOS VALORES= ID_TIPO_DOCUMENTO ='''|| TO_CHAR (:NEW.ID_TIPO_DOCUMENTO)||''', TIPO_DOCUMENTO='''||TO_CHAR (:NEW.TIPO_DOCUMENTO)||'.'
   );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_TIPO_DOCUMENTO
AFTER DELETE ON TBL_TIPO_DOCUMENTO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TIPO_DOCUMENTO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE ELIMINÓ UN REGISTRO CON ID= '|| TO_CHAR (:OLD.ID_TIPO_DOCUMENTO)||' Y LOS VALORES= ID_PERSONA ='''|| TO_CHAR (:OLD.ID_TIPO_DOCUMENTO)||''', TIPO_DOCUMENTO='''||TO_CHAR (:OLD.TIPO_DOCUMENTO)||'.'
   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_TIPO_DOCUMENTO
AFTER UPDATE ON TBL_TIPO_DOCUMENTO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TIPO_DOCUMENTO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    'SE ACTUALIZARON LOS DATOS DEL REGISTRO CON ID= '||TO_CHAR (:OLD.ID_TIPO_DOCUMENTO)||' VALORES ANTERIORES= ID_TIPO_DOCUMENTO ='''|| TO_CHAR (:OLD.ID_TIPO_DOCUMENTO)||
    ''', TIPO_DOCUMENTO='''||TO_CHAR (:OLD.TIPO_DOCUMENTO)|| '.  A VALORES NUEVOS= ID_TIPO_DOCUMENTO ='''|| TO_CHAR (:NEW.ID_TIPO_DOCUMENTO)||''', ID_TIPO_DOCUMENTO='''||TO_CHAR (:NEW.ID_TIPO_DOCUMENTO)||'.'
     );
END;
/


----T_ROL
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_ROL
AFTER INSERT ON TBL_ROL REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_ROL',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    
     'SE IGRESÓ UN NUEVO REGISTRO CON LOS VALORES= '||' ID_STATUS ='''|| TO_CHAR (:NEW.ID_STATUS)||''', ROL='''||TO_CHAR (:NEW.ROL)||
     ''', DESCRIPCION='''||TO_CHAR (:NEW.DESCRIPCION)||'.'
  );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_ROL
AFTER DELETE ON TBL_ROL REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_ROL',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    'SE ELIMINÓ UN REGISTRO CON ID= '|| TO_CHAR (:OLD.ID_ROL)||' Y LOS VALORES= ID_STATUS ='''||
    TO_CHAR (:OLD.ID_STATUS)||''', ROL='''||TO_CHAR (:OLD.ROL)||' DESCRIPCIÓN= '||TO_CHAR (:OLD.DESCRIPCION)||'.'
   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_ROL
AFTER UPDATE ON TBL_ROL REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_ROL',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    'SE ACTUALIZARON LOS DATOS DEL REGISTRO CON ID= '||TO_CHAR (:OLD.ID_ROL)||' VALORES ANTERIORES= ID_ROL ='''|| TO_CHAR (:OLD.ID_ROL)||
    ''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||' ROL= '||TO_CHAR (:OLD.ROL)||' DESCRIPCION= '||TO_CHAR (:NEW.DESCRIPCION)|| '.  A VALORES NUEVOS= ID ='''||TO_CHAR (:NEW.ID_ROL)||' ID_STATUS ='''|| 
    TO_CHAR (:NEW.ID_STATUS)||' ROL= '||TO_CHAR (:NEW.ROL)||' DESCRIPCION= '||TO_CHAR (:NEW.DESCRIPCION)||'.'
    
     );
END;
/











----T_TURNO
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_TURNO
AFTER INSERT ON TBL_TURNO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE IGRESÓ UN NUEVO REGISTRO CON LOS VALORES= '||' ID_STATUS ='''|| TO_CHAR (:NEW.ID_STATUS)||''', TURNO='''||TO_CHAR (:NEW.TURNO)||
     ''', INICIA_TURNO='''||TO_CHAR (:NEW.INICIA_TURNO)||''', FIN_TURNO='''||TO_CHAR (:NEW.FIN_TURNO)||'.'
   );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_TURNO
AFTER DELETE ON TBL_TURNO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
     'SE ELIMINÓ UN REGISTRO CON ID= '|| TO_CHAR (:OLD.ID_TURNO)||' Y LOS VALORES= ID_STATUS ='''|| 
     TO_CHAR (:OLD.ID_STATUS)||''', TURNO='''||TO_CHAR (:OLD.TURNO)||' INICIA_TURNO= '||TO_CHAR (:OLD.INICIA_TURNO)||''', FIN_TURNO='''||TO_CHAR (:OLD.FIN_TURNO)||'.'

   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_TURNO
AFTER UPDATE ON TBL_TURNO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE ACTUALIZO UN REGISTRO CON ID= '|| TO_CHAR (:OLD.ID_TURNO)||' Y LOS VALORES= ID_STATUS ='''|| 
     TO_CHAR (:OLD.ID_STATUS)||''', TURNO='''||TO_CHAR (:OLD.TURNO)||' INICIA_TURNO= '||TO_CHAR (:NEW.INICIA_TURNO)||''', FIN_TURNO='''||TO_CHAR (:NEW.FIN_TURNO)||'.'
     || 'A LOS VALORES NUEVOS ID= '|| TO_CHAR (:NEW.ID_TURNO)||' Y LOS VALORES= ID_STATUS ='''|| 
     TO_CHAR (:NEW.ID_STATUS)||''', TURNO='''||TO_CHAR (:NEW.TURNO)||' INICIA_TURNO= '||TO_CHAR (:NEW.INICIA_TURNO)||''', FIN_TURNO='''||TO_CHAR (:NEW.FIN_TURNO)||'.'

     );
END;
/




----T_TURNO_TIENDA
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_TURNO_TIENDA
AFTER INSERT ON TBL_TURNO_TIENDA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO_TIENDA',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    'SE IGRESÓ UN NUEVO REGISTRO CON LOS VALORES= ID_TIENDA= '||TO_CHAR(:OLD.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:NEW.ID_TURNO)||'.'
   );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_TURNO_TIENDA
AFTER DELETE ON TBL_TURNO_TIENDA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO_TIENDA',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE ELIMINÓ UN REGISTRO CON LOS VALORES= ID_TIENDA= '||TO_CHAR(:OLD.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:OLD.ID_TURNO)||'.'
   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_TURNO_TIENDA
AFTER UPDATE ON TBL_TURNO_TIENDA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO_TIENDA',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE ACTUALIZO UN REGISTRO CON LOS VALORES= ID_TIENDA= '||TO_CHAR(:OLD.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:OLD.ID_TURNO)||
     'A LOS NUEVOS VALORES= ID_TIENDA= '||TO_CHAR(:NEW.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:NEW.ID_TURNO)||'.'
     );
END;
/




----T_TURNO_TIENDA_EMPLEADO
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_TURNO_TIENDA_EMPLEADO
AFTER INSERT ON TBL_TURNO_TIENDA_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO_TIENDA_EMPLEADO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    'SE INGRESÓ UN NUEVO REGISTRO CON LOS VALORES= ID_TIENDA= '||TO_CHAR(:NEW.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:NEW.ID_TURNO)||''', ID_STATUS='''||TO_CHAR (:NEW.ID_STATUS)||
     ''', ID_EMPLEADO='''||TO_CHAR (:NEW.ID_EMPLEADO)||'.'
 
   );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_TURNO_TIENDA_EMPLEADO
AFTER DELETE ON TBL_TURNO_TIENDA_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO_TIENDA_EMPLEADO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
     'SE ELIMINÓ UN REGISTRO CON LOS VALORES= ID_TIENDA= '||TO_CHAR(:OLD.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:OLD.ID_TURNO)||''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||
     ''', ID_EMPLEADO='''||TO_CHAR (:OLD.ID_EMPLEADO)||'.'
   );
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_TURNO_TIENDA_EMPLEADO
AFTER UPDATE ON TBL_TURNO_TIENDA_EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_TURNO_TIENDA_EMPLEADO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
      'SE ACTUALIZÓ UN REGISTRO CON LOS VALORES= ID_TIENDA= '||TO_CHAR(:OLD.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:OLD.ID_TURNO)||''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||
     ''', ID_EMPLEADO='''||TO_CHAR (:OLD.ID_EMPLEADO)||' A LOS VALORES NUEVOS= ID_TIENDA= '||TO_CHAR(:NEW.ID_TIENDA)||' ID_TURNO ='''|| TO_CHAR (:NEW.ID_TURNO)||
     ''', ID_STATUS='''||TO_CHAR (:NEW.ID_STATUS)||
     ''', ID_EMPLEADO='''||TO_CHAR (:NEW.ID_EMPLEADO)||'.'
     );
END;
/



----T_USUARIO
--- insert
create or replace  TRIGGER TGR_BITACORA_AFTER_INSERT_USUARIO
AFTER INSERT ON TBL_USUARIO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_USUARIO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
    'SE INGRESÓ UN NUEVO REGISTRO CON LOS VALORES= ID_USUARIO= '||TO_CHAR(:NEW.ID_USUARIO)||' ID_PERSONA ='''|| TO_CHAR (:NEW.ID_PERSONA)||''', ID_ROL='''||TO_CHAR (:NEW.ID_ROL)||
     ''', ID_USUARIO='''||TO_CHAR (:NEW.USUARIO)||''', CLAVE='''||TO_CHAR (:NEW.CLAVE)||''', ID_STATUS='''||TO_CHAR (:NEW.ID_STATUS)||'.'
    
    
   );
END;
/

---delete


create or replace  TRIGGER TGR_BITACORA_AFTER_DELETE_USUARIO
AFTER DELETE ON TBL_USUARIO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_USUARIO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE ELIMINO REGISTRO CON LOS VALORES= ID_USUARIO= '||TO_CHAR(:OLD.ID_USUARIO)||' ID_PERSONA ='''|| TO_CHAR (:OLD.ID_PERSONA)||''', ID_ROL='''||TO_CHAR (:OLD.ID_ROL)||
     ''', ID_USUARIO='''||TO_CHAR (:OLD.USUARIO)||''', CLAVE='''||TO_CHAR (:OLD.CLAVE)||''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||'.'
     );
    
END;
/

---UPDATE

create or replace  TRIGGER TGR_BITACORA_AFTER_UPDATE_USUARIO
AFTER UPDATE ON TBL_USUARIO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN  
    INSERT INTO TBL_BITACORA (ID_TRANSACCION,BIT_TABLA_PRINCIPAL,TRN_USUARIO,TRN_FECHA_HORA, TRN_LOG)
    VALUES(
    SEC_TBL_BITACORA.NEXTVAL,
    'TBL_USUARIO',
    SYS_CONTEXT ('USERENV', 'OS_USER'),
    SYSDATE,
    
     'SE ACTUALIZO REGISTRO CON LOS VALORES= ID_USUARIO= '||TO_CHAR(:OLD.ID_USUARIO)||' ID_PERSONA ='''|| TO_CHAR (:OLD.ID_PERSONA)||''', ID_ROL='''||TO_CHAR (:OLD.ID_ROL)||
     ''', ID_USUARIO='''||TO_CHAR (:OLD.USUARIO)||''', CLAVE='''||TO_CHAR (:OLD.CLAVE)||''', ID_STATUS='''||TO_CHAR (:OLD.ID_STATUS)||'.'||
    
    
     ' A LOS VALORES NUEVOS = ID_USUARIO= '||TO_CHAR(:NEW.ID_USUARIO)||' ID_PERSONA ='''|| TO_CHAR (:NEW.ID_PERSONA)||''', ID_ROL='''||TO_CHAR (:NEW.ID_ROL)||
     ''', ID_USUARIO='''||TO_CHAR (:NEW.USUARIO)||''', CLAVE='''||TO_CHAR (:NEW.CLAVE)||''', ID_STATUS='''||TO_CHAR (:NEW.ID_STATUS)||'.'
    
     );
END;
/






COMMIT;












----------- alteracion tabla turno campos inicia_turno y fin _turno 
 alter table tbl_turno
  modify INICIA_TURNO VARCHAR(5)

  CONSTRAINT INICIA_TURNO CHECK(
    SUBSTR(INICIA_TURNO, 1, 2) BETWEEN 00 AND 23
    AND SUBSTR(INICIA_TURNO, 4, 2) BETWEEN 00 AND 59
    AND SUBSTR(INICIA_TURNO, 3, 1) = ':'
  );
  
  
   alter table tbl_turno
  modify FIN_TURNO VARCHAR(5)

  CONSTRAINT FIN_TURNO CHECK(
    SUBSTR(FIN_TURNO, 1, 2) BETWEEN 00 AND 23
    AND SUBSTR(FIN_TURNO, 4, 2) BETWEEN 00 AND 59
    AND SUBSTR(FIN_TURNO, 3, 1) = ':'
  );
  
  
  COMMIT;




 
 ---EMPLEADOS, NO ASIGNADOS
 CREATE OR REPLACE VIEW V_EMPLEADOS_NO_ASIGNADOS
 AS 
 select E.id_empleado,E.fecha_ingreso,E.id_status,st.status,P.id_persona,P.primer_nombre,P.segundo_nombre,P.tercer_nombre,
 P.primero_apellido,P.segundo_apellido,P.id_tipo_documento,D.tipo_documento,P.documento,P.nit,P.fecha_nacimiento,P.sexo,P.telefono,P.email,P.direccion
 from tbl_empleado E
 inner join tbl_persona P on E.id_persona = P.id_persona
  left join tbl_turno_tienda_empleado tte on E.id_empleado = tte.id_empleado
left join tbl_usuario U on  P.id_persona = U.id_persona
 inner join tbl_status st on E.id_status = st.id_status
   inner join tbl_tipo_documento D on P.id_tipo_documento = D.id_tipo_documento
where u.id_usuario is null and tte.id_empleado is null;





 


 SELECT * FROM V_EMPLEADOS_NO_ASIGNADOS;
 


SELECT * FROM V_EMPLEADOS_ASIGNADOS;
 
 CREATE OR REPLACE VIEW V_EMPLEADOS_ASIGNADOS 
 AS 
 select E.ID_EMPLEADO,E.ID_STATUS,st.status,E.FECHA_INGRESO,
 P.ID_PERSONA,P.PRIMER_NOMBRE,P.SEGUNDO_NOMBRE,P.TERCER_NOMBRE,P.PRIMERO_APELLIDO,P.SEGUNDO_APELLIDO,
 P.ID_TIPO_DOCUMENTO,D.TIPO_DOCUMENTO,
 P.DOCUMENTO,P.NIT,P.FECHA_NACIMIENTO,P.SEXO,P.TELEFONO,P.EMAIL,P.DIRECCION,
 U.ID_USUARIO,U.USUARIO,U.ID_ROL, R.ROL,U.CLAVE,
 tte.id_tienda,ti.tienda,tte.id_turno,t.turno,t.inicia_turno,t.fin_turno
 from tbl_empleado E
 inner join tbl_status st on E.id_status = st.id_status
 inner join tbl_persona P on E.id_persona = P.id_persona
  inner join tbl_tipo_documento D on P.id_tipo_documento = D.id_tipo_documento
 inner join tbl_usuario U on  P.id_persona = U.id_persona
 inner join tbl_rol R on U.id_rol = R.id_rol
 inner join tbl_turno_tienda_empleado tte on E.id_empleado = tte.id_empleado
  inner join tbl_turno_tienda tt on tte.id_tienda = tt.id_tienda and tte.id_turno =tt.id_turno
   inner join tbl_turno t on tt.id_turno = t.id_turno
 inner join tbl_tienda ti on tt.id_tienda = ti.id_tienda
 ;
 
 commit;
 
 SELECT * FROM V_EMPLEADOS_ASIGNADOS;
 

CREATE OR REPLACE VIEW V_turno_tienda
 AS 
select tt.id_tienda,ti.tienda,tt.id_turno,tu.turno
from tbl_turno_tienda tt
inner join tbl_turno tu on tt.id_turno = tu.id_turno
inner join tbl_tienda ti on tt.id_tienda = ti.id_tienda;


select * from v_turno_tienda;


 


