CREATE SEQUENCE SEC_TBL_CATEGORIA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 15
INCREMENT BY 1
CACHE 20;

--T_CATEGORIA

create or replace  TRIGGER TGR_CATEGORIA
BEFORE INSERT ON TBL_CATEGORIA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT SEC_TBL_CATEGORIA.NEXTVAL INTO :New.ID_CATEGORIA  FROM DUAL;

END;
