--TIENDA
CREATE SEQUENCE SEC_TBL_TIENDA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 5
INCREMENT BY 1
CACHE 20;


--TIENDA
create or replace  TRIGGER TGR_TIENDA
BEFORE INSERT ON TBL_TIENDA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT SEC_TBL_TIENDA.NEXTVAL INTO :New.ID_TIENDA FROM DUAL;

END;
