---SECUENCIAS---
--TBL_GASOLINERA
CREATE SEQUENCE SEC_TBL_GASOLINERA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 6
INCREMENT BY 1
CACHE 20;

drop sequence SEC_TBL_GASOLINERA;
create sequence SEC_TBL_GASOLINERA increment by 1; 


--TBL_GASOLINERA
create or replace  TRIGGER TGR_GASOLINERA
BEFORE INSERT ON TBL_GASOLINERA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT SEC_TBL_GASOLINERA.NEXTVAL INTO :New.ID_GASOLINERA  FROM DUAL;

END;


COMMIT;
