---SECUENCIAS---

--TBL_GASOLINERA
CREATE SEQUENCE SEC_TBL_GASOLINERA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

--TIENDA
CREATE SEQUENCE SEC_TBL_TIENDA
MINVALUE 1
MAXVALUE 99999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

--TRIGGERS--

--TBL_GASOLINERA
create or replace  TRIGGER TGR_GASOLINERA
BEFORE INSERT ON TBL_GASOLINERA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT SEC_TBL_GASOLINERA.NEXTVAL INTO :New.ID_GASOLINERA  FROM DUAL;

END;

--TIENDA
create or replace  TRIGGER TGR_TIENDA
BEFORE INSERT ON TBL_TIENDA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT SEC_TBL_TIENDA.NEXTVAL INTO :New.ID_TIENDA FROM DUAL;

END;