create or replace  TRIGGER TGR_TIPO_DOCUMENTO
BEFORE INSERT ON TBL_TIPO_DOCUMENTO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT SEC_TBL_TIPO_DOCUMENTO.NEXTVAL INTO :New.ID_TIPO_DOCUMENTO  FROM DUAL;

END;
/